"use client";

import "./globals.scss";
import { Inter } from "next/font/google";
import Providers from "@/components/Providers";
import { useEffect } from "react";
import Navbar from "@/components/Navbar";
import { usePathname } from "next/navigation";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  useEffect(() => {
    import("preline");
  }, []);

  const pathname = usePathname();
  const showNavbar =
    pathname !== "/auth/signin" &&
    pathname !== "/auth/verify-request" &&
    pathname !== "/auth/new-user";
  const showFooter = showNavbar;

  return (
    <html lang="en" className={`h-full ${inter.className}`}>
      <body
        className={` dark:bg-slate-900 flex flex-col min-h-full ${
          !showNavbar && "bg-gray-100 justify-center items-center py-16"
        }`}
      >
        <Providers>
          {showNavbar && <Navbar />}
          {children}
          {showFooter && <Footer />}
        </Providers>
      </body>
    </html>
  );
}
